name: example_console
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.1
description: >
  In teaching programming a console with interactive communication between a
  user and a program is useful for learners and a teacher. For example, a teacher
  may give an assignment to do several programming exercises. Students write those
  programming exercises and prompt a teacher to execute them. Or, a teacher gives
  for each subject matter several examples that students can execute.
dependencies:
  browser: any
