name: example_console
version: 0.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: In teaching programming a console with interactive communication between a user and a program is useful for learners and a teacher. For example, a teacher may give an assignment to do several programming exercises. Students write those programming exercises and prompt a teacher to execute them. Or, a teacher gives for each subject matter several examples that students can execute.
homepage: http://ondart.me/
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
